"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Search } from "lucide-react";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function Hero() {
  const router = useRouter();
  const [tab, setTab] = useState("Buy");
  const [location, setLocation] = useState("");
  const [type, setType] = useState("");
  const [price, setPrice] = useState("");
  const [imageUnavailable, setImageUnavailable] = useState(false);
  const submit = (event: FormEvent) => { event.preventDefault(); const params = new URLSearchParams(); if (location) params.set("location", location); if (type) params.set("type", type); if (price) params.set("max", price); if (tab === "Rent") params.set("listing", "For Rent"); if (tab === "Buy") params.set("listing", "For Sale"); if (tab === "Commercial") params.set("type", "Commercial"); router.push(`/properties?${params.toString()}`); };
  return <section className="bg-white pb-12 pt-4 sm:pb-16"><div className="container-page"><div className="relative min-h-[31rem] overflow-hidden bg-[#071A2F] sm:min-h-[34rem]">{imageUnavailable ? <div className="absolute inset-0 bg-[linear-gradient(120deg,#04111F,#0B2745)]" aria-hidden="true" /> : <Image preload onError={() => setImageUnavailable(true)} src="/images/properties/photo-1600585154340-be6161a56a0c.jpg" alt="Contemporary residence at dusk" fill sizes="100vw" className="object-cover" />}<div className="absolute inset-0 bg-gradient-to-r from-[#04111F]/90 via-[#071A2F]/50 to-transparent" /><div className="relative flex min-h-[31rem] max-w-xl flex-col justify-center px-7 py-14 text-white sm:min-h-[34rem] sm:px-12"><p className="eyebrow !text-[#E6BE7C]">Thoughtful places to live</p><h1 className="font-display mt-4 text-4xl font-bold leading-[1.05] sm:text-6xl">Find Your<br />Perfect Home</h1><p className="mt-5 max-w-md text-sm leading-6 text-slate-100 sm:text-base">Explore thoughtfully selected homes, apartments, and investment properties designed around the way you want to live.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/properties" className="btn-primary !border-[#C99545] !bg-[#C99545] hover:!border-white hover:!bg-white hover:!text-[#071A2F]">Explore Properties <ArrowRight size={15} /></Link><Link href="/about" className="btn-outline text-white">Learn More</Link></div></div></div><form onSubmit={submit} className="relative z-10 mx-auto -mt-8 w-[calc(100%-1.5rem)] max-w-5xl rounded-md bg-white p-4 shadow-[0_12px_34px_rgb(15_23_42/.14)] sm:p-6"><div className="flex gap-6 border-b border-slate-200"><Tabs label="Buy" active={tab} setTab={setTab} /><Tabs label="Rent" active={tab} setTab={setTab} /><Tabs label="Commercial" active={tab} setTab={setTab} /></div><div className="mt-5 grid gap-3 md:grid-cols-[1.35fr_1fr_1fr_auto]"><div><label className="label" htmlFor="hero-location">Location</label><input id="hero-location" value={location} onChange={(e) => setLocation(e.target.value)} className="input" placeholder="City or neighborhood" /></div><div><label className="label" htmlFor="hero-type">Property Type</label><select id="hero-type" value={type} onChange={(e) => setType(e.target.value)} className="input"><option value="">All Types</option><option>House</option><option>Apartment</option><option>Villa</option><option>Townhouse</option></select></div><div><label className="label" htmlFor="hero-price">Maximum Price</label><select id="hero-price" value={price} onChange={(e) => setPrice(e.target.value)} className="input"><option value="">Any price</option><option value="750000">Up to $750,000</option><option value="1000000">Up to $1,000,000</option><option value="1500000">Up to $1,500,000</option></select></div><button className="btn-primary self-end !py-[.8rem]" type="submit"><Search size={15} />Search</button></div></form></div></section>;
}
function Tabs({ label, active, setTab }: { label: string; active: string; setTab: (value: string) => void }) { return <button type="button" onClick={() => setTab(label)} className={`border-b-2 px-2 pb-3 text-xs font-bold transition ${active === label ? "border-[#C99545] text-[#071A2F]" : "border-transparent text-slate-400 hover:text-[#071A2F]"}`}>{label}</button>; }
