"use client";

import { SlidersHorizontal, X } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import { properties } from "@/data/properties";
import { PropertyCard } from "./PropertyCard";

const types = ["House", "Apartment", "Villa", "Townhouse", "Commercial"];

export function PropertyExplorer() {
  const search = useSearchParams();
  const [drawer, setDrawer] = useState(false);
  const [filters, setFilters] = useState(() => ({ location: search.get("location") ?? "", listing: search.get("listing") ?? "", type: search.get("type") ?? "", min: search.get("min") ?? "", max: search.get("max") ?? "", beds: search.get("beds") ?? "", baths: search.get("baths") ?? "" }));
  const [sort, setSort] = useState(search.get("sort") ?? "relevant");
  const update = (key: keyof typeof filters, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  const navigate = (nextFilters = filters, nextSort = sort) => { const params = new URLSearchParams(); Object.entries(nextFilters).forEach(([key, value]) => { if (value) params.set(key, value); }); if (nextSort !== "relevant") params.set("sort", nextSort); window.history.replaceState(null, "", `/properties${params.size ? `?${params}` : ""}`); };
  const apply = () => { navigate(); setDrawer(false); };
  const reset = () => { setFilters({ location: "", listing: "", type: "", min: "", max: "", beds: "", baths: "" }); setSort("relevant"); window.history.replaceState(null, "", "/properties"); setDrawer(false); };
  const results = useMemo(() => properties.filter((property) => {
    const city = `${property.city} ${property.location}`.toLowerCase();
    return (!filters.location || city.includes(filters.location.toLowerCase())) && (!filters.listing || property.listingType === filters.listing) && (!filters.type || property.propertyType === filters.type) && (!filters.min || property.price >= Number(filters.min)) && (!filters.max || property.price <= Number(filters.max)) && (!filters.beds || property.bedrooms >= Number(filters.beds)) && (!filters.baths || property.bathrooms >= Number(filters.baths));
  }).sort((a, b) => sort === "low" ? a.price - b.price : sort === "high" ? b.price - a.price : sort === "new" ? b.createdAt.localeCompare(a.createdAt) : 0), [filters, sort]);
  const fields = <><FilterLabel label="Location"><input className="input" value={filters.location} onChange={(e) => update("location", e.target.value)} placeholder="City or neighborhood" /></FilterLabel><FilterLabel label="Listing type"><select className="input" value={filters.listing} onChange={(e) => update("listing", e.target.value)}><option value="">All listings</option><option>For Sale</option><option>For Rent</option></select></FilterLabel><FilterLabel label="Property type"><select className="input" value={filters.type} onChange={(e) => update("type", e.target.value)}><option value="">All property types</option>{types.map((type) => <option key={type}>{type}</option>)}</select></FilterLabel><div className="grid grid-cols-2 gap-3"><FilterLabel label="Min. price"><input inputMode="numeric" className="input" value={filters.min} onChange={(e) => update("min", e.target.value)} placeholder="$0" /></FilterLabel><FilterLabel label="Max. price"><input inputMode="numeric" className="input" value={filters.max} onChange={(e) => update("max", e.target.value)} placeholder="No max" /></FilterLabel></div><div className="grid grid-cols-2 gap-3"><FilterLabel label="Bedrooms"><select className="input" value={filters.beds} onChange={(e) => update("beds", e.target.value)}><option value="">Any</option>{[1, 2, 3, 4, 5].map((number) => <option key={number} value={number}>{number}+</option>)}</select></FilterLabel><FilterLabel label="Bathrooms"><select className="input" value={filters.baths} onChange={(e) => update("baths", e.target.value)}><option value="">Any</option>{[1, 2, 3, 4].map((number) => <option key={number} value={number}>{number}+</option>)}</select></FilterLabel></div></>;
  const panel = <div className="space-y-4"><div className="flex items-center justify-between"><h2 className="text-sm font-bold text-[#071A2F]">Filter properties</h2><button type="button" onClick={reset} className="text-xs font-semibold text-[#C99545] hover:text-[#071A2F]">Reset all</button></div>{fields}<button type="button" onClick={apply} className="btn-primary w-full">Apply Filters</button></div>;
  return <><div className="container-page py-10 sm:py-14"><div className="mb-8"><p className="eyebrow">Available properties</p><h1 className="font-display mt-2 text-4xl font-bold text-[#071A2F]">Properties</h1><p className="mt-3 text-sm text-slate-500">Browse spaces designed for the way you want to live and work.</p></div><div className="grid gap-8 lg:grid-cols-[16.5rem_1fr]"><aside className="hidden h-fit rounded-md border border-slate-200 bg-white p-5 lg:block">{panel}</aside><div><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-500">Showing <span className="font-bold text-[#071A2F]">{results.length}</span> {results.length === 1 ? "property" : "properties"}</p><div className="flex items-center gap-2"><button type="button" onClick={() => setDrawer(true)} className="btn-outline !py-2 lg:hidden"><SlidersHorizontal size={15} />Filters</button><label className="sr-only" htmlFor="sort">Sort properties</label><select id="sort" className="input !w-auto !py-2 text-xs" value={sort} onChange={(e) => { const nextSort = e.target.value; setSort(nextSort); navigate(filters, nextSort); }}><option value="relevant">Most Relevant</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option><option value="new">Newest</option></select></div></div>{results.length ? <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{results.map((property, index) => <PropertyCard key={property.id} property={property} eager={index === 0} />)}</div> : <EmptyState reset={reset} />}</div></div></div>{drawer && <div className="fixed inset-0 z-[60] bg-[#04111F]/50 lg:hidden" role="dialog" aria-modal="true" aria-label="Property filters"><div className="ml-auto h-full w-[min(100%,23rem)] overflow-y-auto bg-white p-6"><div className="mb-6 flex items-center justify-between"><h2 className="font-display text-2xl font-bold text-[#071A2F]">Filters</h2><button type="button" onClick={() => setDrawer(false)} className="grid size-9 place-items-center border border-slate-200" aria-label="Close filters"><X size={17} /></button></div>{panel}</div></div>}</>;
}
function FilterLabel({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="label">{label}</span>{children}</label>; }
function EmptyState({ reset }: { reset: () => void }) { return <div className="border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><h2 className="font-display text-2xl font-bold text-[#071A2F]">No properties found</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">Try removing a filter or adjusting your price range to see more matching properties.</p><button type="button" onClick={reset} className="btn-primary mt-5">Clear filters</button></div>; }
