import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Mail, MapPin, Phone, ArrowLeft } from "lucide-react";
import { notFound } from "next/navigation";
import { agents } from "@/data/agents";
import { properties } from "@/data/properties";
import { PropertyCard } from "@/components/property/PropertyCard";
export function generateStaticParams() { return agents.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const agent = agents.find((item) => item.slug === slug); return { title: agent?.name ?? "Agent not found" }; }
export default async function AgentPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const agent = agents.find((item) => item.slug === slug); if (!agent) notFound(); const agentProperties = properties.filter((property) => property.agentId === agent.id).slice(0, 3); return <main><section className="container-page py-8 sm:py-14"><Link href="/agents" className="inline-flex items-center gap-2 text-xs font-bold text-slate-500 hover:text-[#C99545]"><ArrowLeft size={14} />All agents</Link><div className="mt-6 grid overflow-hidden border border-slate-200 bg-white md:grid-cols-[.8fr_1.2fr]"><div className="relative min-h-80"><Image src={agent.image} alt={agent.name} fill sizes="(max-width: 768px) 100vw, 40vw" className="object-cover" /></div><div className="p-7 sm:p-10"><p className="eyebrow">{agent.role}</p><h1 className="font-display mt-3 text-4xl font-bold text-[#071A2F]">{agent.name}</h1><p className="mt-3 text-sm font-semibold text-[#C99545]">{agent.specialty}</p><p className="prose-copy mt-5">{agent.bio}</p><dl className="mt-7 grid gap-4 border-t border-slate-100 pt-5 text-sm text-slate-600"><div className="flex items-center gap-2"><MapPin size={16} className="text-[#C99545]" />{agent.location} · {agent.experience}</div><a href={`tel:${agent.phone}`} className="flex items-center gap-2 hover:text-[#C99545]"><Phone size={16} className="text-[#C99545]" />{agent.phone}</a><a href={`mailto:${agent.email}`} className="flex items-center gap-2 hover:text-[#C99545]"><Mail size={16} className="text-[#C99545]" />{agent.email}</a></dl></div></div>{agentProperties.length > 0 && <section className="mt-16"><p className="eyebrow">Selected properties</p><h2 className="font-display mt-2 text-3xl font-bold text-[#071A2F]">Properties with {agent.name.split(" ")[0]}</h2><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{agentProperties.map((property) => <PropertyCard key={property.id} property={property} />)}</div></section>}</section></main>; }
